# Generated by Django 4.2.2 on 2023-06-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='iventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='tittle',
            new_name='title',
        ),
    ]
